### ISSUE TITLE
Dropdown not clickable if on top of other gui components

### ISSUE THREAD

**Issue by hamoid** [roymacdonald/ofxDropdown#12]
If there are other panels where the dropdown is shown, it is not possible to click on those items. Even if I changed the order to make sure the dropdown is drawn last, the mouse movements are captured by the other gui. Maybe the first component to be drawn is the one that gets the the mouse input.

For now I'll tell the user to collapse the conflicting panel if they want to change the song.

![image](https://user-images.githubusercontent.com/108264/173764751-e24fcb5e-6302-4808-a742-2ca5f28d7a71.png)

**Comment by roymacdonald** [comment]
that has to do with the event priority of the whole gui. it gets set when the mouse events are registered. 
even when you can change the default event priority for ofxGui it is stored as an enum type instead of an int, and the default is already the lowest.
So, a work around would be to listen to each dropdowns `dropdownWillShow_E` event, and call  `unregisterMouseEvents();` on the gui that gets hidden by the dropdown. Then you also listen to the dropdown's dropdownHidden_E so when it gets hidden you call `registerMouseEvents();` on the gui that gets hidden by the dropdown.
There is a work around to this by setting the events priorities for the dropdown to be lower (happens first) but it is more cumbersome. I will add it to the addon, so it is handled internaly.

**Comment by roymacdonald** [comment]
Hi. A just pushed an update that should deal with this issue automatically.
can you check if it works for you? It does work for me.

**Comment by hamoid** [comment]
I'll check at the end of July :)

**Comment by hamoid** [comment]
Hi! Back updating this project...

I think there are still some issues. I can see through the dropdown options and mouse events go to whatever is behind the dropdown.

https://user-images.githubusercontent.com/108264/199544863-24a1196a-73f3-496a-bc33-b5248481cad4.mp4

**Comment by roymacdonald** [comment]
Hey, Thanks for letting me know. I now realized why the previous "fix" I made did not work.
I am using this addon a lot so I will get it fixed soon.

**Comment by roymacdonald** [comment]
Hey! Sorry it took me so long to add this feature. Now it is implemented along with several other. Check the ofxDropdown.h file for the new functions. All have inline documentation. 
As for the feature you ask for to work you only need to update to the newest version of this addon.
