### ISSUE TITLE
How using dropdown inside a ofParameterGroup? 

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxDropdown#15]
Is it possible to use the dropdown menu as part of a ofParameterGroup? 
Or can it only be part of an ofxPanel ?
```
//in ofApp.h
ofParamaterGroup group_test;

//in ofApp.cpp
    group_test.setName("test group");
    intOptions.setName("INT Options");
    intDropdown =  make_unique<ofxIntDropdown>(intOptions);
    group_test.add(intDropdown->getDropdownParameters());

    for(int i = 0; i < 15; i++){
            intDropdown->add(i, "Opcion " + ofToString(i));
    }
    group_test.add(intDropdown.get());
    gui.add(group_test);
```

**Comment by roymacdonald** [comment]
Yes and no. You cant use it with an ofParameterGroup, but you can with an ofxguigroup. I can check later the correct way for doing such and post here

**Comment by roymacdonald** [comment]
FYI.
Instead of instancing an `ofParameterGroup` use an `ofxGuiGroup`. It works almost the same. 

```
ofxDropdown dropdown;
// setup, etc
ofParameterGroup paramGroup;

paramGroup.add(dropdown);// THIS DOES NOT WORK.

ofxGuiGroup guiGroup;
guiGroup.setup(...);
guiGroup.add(&dropdown); // THIS WORKS. Notice that there is an & before "dropdown". this is needed to "dereference" the variable and make it a pointer.

```
Now, as you have an `ofxGuiGroup` you CAN NOT put it inside another `ofParameterGroup`, thus you need to do the same, use another `ofxGuiGroup` instead.

As a rule of thumb, any `ofxGui` element, such as `ofxDropdown` and `ofxGuiGroup` can only get added into another `ofxGuiGroup` (or `ofxPanel`, which inherits from `ofxGuiGroup`). 
On the other hand, any `ofParameter` or `ofParameterGroup` can get added into either a `ofParameterGroup` or `ofxGuiGroup`.
